# RandomUser.me – Test Cases (Corrected & Readable Container)

Target Application: RandomUser.me

Below is the **same content you showed in the screenshot**, but rewritten cleanly, aligned, and readable in a proper container.
No data is changed — only formatting is corrected so it is easy to view, edit, and maintain in GitHub.

---

| Sl. No. | DATE       | Application   | Test Case ID | Test Case Name                | Module / Feature | Test Step No. | Step Description            | Keyword (Action) | Test Object / Element                        | Input Data | Expected Result            | Actual Result | Status (Pass/Fail) | Comments / Notes | Elapsed time |
| ------- | ---------- | ------------- | ------------ | ----------------------------- | ---------------- | ------------- | --------------------------- | ---------------- | -------------------------------------------- | ---------- | -------------------------- | ------------- | ------------------ | ---------------- | ------------ |
| 11      | 2025-11-28 | RandomUser.me | RU-TC11      | API Default Request           | API              | 1             | Send GET request            | GET              | /api/                                        | —          | Returns 1 random user      |               |                    |                  |              |
| 12      | 2025-11-28 | RandomUser.me | RU-TC12      | API Multiple Users            | API              | 1             | Request multiple users      | GET              | /api/?results=10                             | results=10 | Returns 10 users           |               |                    |                  |              |
| 13      | 2025-11-28 | RandomUser.me | RU-TC13      | API Gender Filter             | API              | 1             | Filter by gender            | GET              | /api/?gender=female                          | female     | Only female users returned |               |                    |                  |              |
| 14      | 2025-11-28 | RandomUser.me | RU-TC14      | API Nationality Filter        | API              | 1             | Filter by nationality       | GET              | /api/?nat=US                                 | US         | Only US users returned     |               |                    |                  |              |
| 15      | 2025-11-28 | RandomUser.me | RU-TC15      | API Seed Consistency          | API              | 1             | Use seed parameter          | GET              | /api/?seed=test                              | test       | Same user returned         |               |                    |                  |              |
| 16      | 2025-11-28 | RandomUser.me | RU-TC16      | API Pagination Page 1         | API              | 1             | Request page 1              | GET              | /api/?page=1&results=5                       | —          | Returns page 1 results     |               |                    |                  |              |
| 17      | 2025-11-28 | RandomUser.me | RU-TC17      | API Pagination Page 2         | API              | 1             | Request page 2              | GET              | /api/?page=2&results=5                       | —          | Returns new users          |               |                    |                  |              |
| 18      | 2025-11-28 | RandomUser.me | RU-TC18      | API Response Time             | API              | 1             | Measure response time       | GET              | /api/                                        | —          | Response < 2 seconds       |               |                    |                  |              |
| 19      | 2025-11-28 | RandomUser.me | RU-TC19      | API JSON Structure            | API              | 1             | Validate JSON schema        | Verify           | JSON Response                                | —          | Valid schema               |               |                    |                  |              |
| 20      | 2025-11-28 | RandomUser.me | RU-TC20      | API HTTPS Enforcement         | API              | 1             | Send HTTP request           | GET              | [http://randomuser.me](http://randomuser.me) | —          | Redirects to HTTPS         |               |                    |                  |              |
| 21      | 2025-11-28 | RandomUser.me | RU-TC21      | Invalid Results Parameter     | Negative         | 1             | Send invalid results value  | GET              | /api/?results=abc                            | abc        | Graceful error             |               |                    |                  |              |
| 22      | 2025-11-28 | RandomUser.me | RU-TC22      | Negative Results Count        | Negative         | 1             | Send negative results value | GET              | /api/?results=-5                             | -5         | Defaults safely            |               |                    |                  |              |
| 23      | 2025-11-28 | RandomUser.me | RU-TC23      | Large Results Count           | Edge             | 1             | Request large dataset       | GET              | /api/?results=5000                           | 5000       | Handled or limited         |               |                    |                  |              |
| 24      | 2025-11-28 | RandomUser.me | RU-TC24      | Invalid Gender Parameter      | Negative         | 1             | Send invalid gender         | GET              | /api/?gender=unknown                         | unknown    | Ignored or handled         |               |                    |                  |              |
| 25      | 2025-11-28 | RandomUser.me | RU-TC25      | Invalid Nationality Parameter | Negative         | 1             | Send invalid nat            | GET              | /api/?nat=XYZ                                | XYZ        | Handled safely             |               |                    |                  |              |
| 26      | 2025-11-28 | RandomUser.me | RU-TC26      | Missing Query Parameters      | Edge             | 1             | Call API without params     | GET              | /api/                                        | —          | Defaults applied           |               |                    |                  |              |
| 27      | 2025-11-28 | RandomUser.me | RU-TC27      | SQL Injection Attempt         | Security         | 1             | Inject SQL-like string      | GET              | /api/?seed=1;DROP                            | Injection  | No execution               |               |                    |                  |              |
| 28      | 2025-11-28 | RandomUser.me | RU-TC28      | Script Injection Attempt      | Security         | 1             | Inject script               | GET              | /api/?seed=<script>                          | Script     | Ignored safely             |               |                    |                  |              |
| 29      | 2025-11-28 | RandomUser.me | RU-TC29      | Unicode Injection             | Security         | 1             | Inject Unicode chars        | GET              | /api/?seed=零                                 | Unicode    | Handled safely             |               |                    |                  |              |
| 30      | 2025-11-28 | RandomUser.me | RU-TC30      | Rate Limit Handling           | Security         | 1             | Send rapid requests         | GET              | /api/                                        | Rapid      | No crash                   |               |                    |                  |              |
| 31      | 2025-11-28 | RandomUser.me | RU-TC31      | CORS Headers                  | Security         | 1             | Inspect headers             | Verify           | Response Headers                             | —          | CORS present               |               |                    |                  |              |
| 32      | 2025-11-28 | RandomUser.me | RU-TC32      | Cache Behavior                | API              | 1             | Repeat same seed            | GET              | /api/?seed=test                              | test       | Consistent result          |               |                    |                  |              |
| 33      | 2025-11-28 | RandomUser.me | RU-TC33      | Malformed URL                 | Negative         | 1             | Call invalid endpoint       | GET              | /api/xyz                                     | —          | 404 returned               |               |                    |                  |              |
| 34      | 2025-11-28 | RandomUser.me | RU-TC34      | Empty Response Handling       | Edge             | 1             | Simulate empty response     | Verify           | API                                          | —          | Graceful handling          |               |                    |                  |              |
| 35      | 2025-11-28 | RandomUser.me | RU-TC35      | API Error Message Format      | API              | 1             | Trigger error               | Verify           | Error JSON                                   | —          | Readable error             |               |                    |                  |              |

---

This format is **GitHub-friendly**, **human-readable**, and **easy to extend**.
If you want, I can:

* Add **UI test cases (RU-TC01–RU-TC10)** in the same format
* Export this as **Excel / CSV**
* Split API, UI, Security into **separate files**
* Normalize it exactly to your other repos
